### PR TITLE
Initial implementation of provisioned appx methods.

### LINKED ISSUE #10: Provisioned Appx API
DismApi contains some internal functions and I'm able to implement them. I know you aren't happy with introducing undocumented functions to code (for good reason), but some open source projects exposes internal API in different namespace with warning about possibility of future break changes.

I propose to create public static class InternalDismApi (or DismApiInternal?) exposing DISM functions:

_DismAddProvisionedAppxPackage
_DismGetProvisionedAppxPackages
_DismRemoveProvisionedAppxPackage

I need them for my application. Of course, if you don't want them, I will implement these functions only in my application :)

### PR DESCRIPTION
**Pull request by josemesona**
These were taken from the DISM PowerShell module

@MichalPavlik can you make sure this looks good for you?

Closes #10

### CODE REVIEW

**Comment by MichalPavlik** [comment]
I tried all 3 methods in Appx branch on live system and it's working.
Maybe the `_AddProvisionedAppxPackage` method can be simplified. Combination of `licensePath = null` and `skipLicense = false` is invalid. I propose to exclude `skipLicense` parameter from `DismApi._AddProvisionedAppxPackage` and compute value internally as `skipLicense = String.IsNullOrEmpty(licensePath)`. What do you think?

**Comment by josemesona** [comment]
Okay I updated the method to remove `skipLicense`.  I also had forgotten to implement `Equals()` and `GetHashCode()` on the `DismAppxPackage` class.

**Comment by MichalPavlik** [comment]
Great. And you can declare, that your classes implements strongly typed `IEquatable<T>` because you already implemented this interface :)

And I noticed, that `DismProcessorArchitecture` enumeration isn't probably correct for `DismAppxPackage.Architecture` property. All packages on my system are neutral and the value is 11. So the original enum can be [Windows.System.ProcessorArchitecture](https://msdn.microsoft.com/en-us/library/windows/apps/windows.system.processorarchitecture). Values 0 and 9 are same, but I'm not sure if this enum is interchangeable.

**Comment by josemesona** [comment]
I'll just add Neutral to `DismProcessorArchitecture`

**Comment by msftphil** [comment]
Heads-up, between RS3 and RS4 the API signature of _DismAddProvisionedAppxPackage was changed.

**Pull request merged**
